### ISSUE TITLE
File Structure & Naming Conventions

### ISSUE THREAD

**Issue by tbeidlershenk** [Steelhacks-2023/Lost-and-Found-Steelhacks#13]
Title ^ Just need to organize the codebase

**Comment by jeffzheng13** [comment]
So are pages capital CamelCase or camelCase and then classes are capital CamelCase I'm pretty sure, right? Just trying to establish now so we can maintain a cleaner and tidy-er codebase.

**Comment by tbeidlershenk** [comment]
@jeffzheng13 yep that's the Flutter standard so we'll go with that
